name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: python -m pip install pytest pytest-cov webdavclient3 requests boto3 pyyaml aiohttp liboidcagent

    - name: Run tests
      run: python -m pytest tests --cov=oscar_python
